name: Context testing
on: push

jobs:
  dump_contexts-to_log:
    runs-on: ubuntu_latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
